### PR TITLE
Add bower support

### PR DESCRIPTION
**Pull request by misterion**
Subj

### CODE REVIEW

**Comment by gustavnikolaj** [comment]
I have never used bower, so please correct me if I'm wrong.

I'll be happy to merge this, when we have worked through the comments I posted :-)

**Comment by misterion** [comment]
I removed the dependency. Yes, it`s possible to use git url as bower component source but much more comfortable to use it via bower install.

**Comment by gustavnikolaj** [comment]
You should have dependencies matching the ones in package.json, otherwise the plugin won't work.

Wouldn't you be able to install from github by running: `bower install One-com/knockout-popupTemplate`?

**Comment by misterion** [comment]
Yes, thanx.

**Comment by gustavnikolaj** [comment]
If you reintroduce the (correct) dependencies, and remove the version tag, I'll merge immediately.

**Comment by gustavnikolaj** [comment]
@misterion Haven't heard back from you yet, so I'll be closing this PR. Please reopen if it's still relevant to you.

**Pull request closed without merging**
